using FileExplorerUI.Collections;
using FileExplorerUI.Commands;
using FileExplorerUI.Controls;
using FileExplorerUI.Interop;
using FileExplorerUI.Settings;
using FileExplorerUI.Services;
using FileExplorerUI.Workspace;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using Microsoft.UI.Xaml.Media;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Windows.ApplicationModel.DataTransfer;

namespace FileExplorerUI
{
    public sealed partial class MainWindow
    {
        private GridLength _nameColumnWidth = new(220);
        private GridLength _typeColumnWidth = new(150);
        private GridLength _sizeColumnWidth = new(120);
        private GridLength _modifiedColumnWidth = new(180);
        private GridLength _sidebarColumnWidth = new(220);
        private double _detailsContentWidth = 694;
        private double _detailsRowWidth = 714;
        private UIElement? _activeSplitterElement;
        private SplitterDragMode _activeSplitterDragMode;
        private ColumnSplitterKind? _activeColumnSplitterKind;
        private ColumnResizeState? _activeColumnResizeState;
        private double _splitterDragStartX;
        private double? _sidebarDragStartWidth;
        private int _splitterHoverCount;
        private double _sidebarPreferredExpandedWidth = 220;
        private bool _isSidebarCompact;
        private bool _sidebarPinnedCompact;
        private TreeView? _sidebarTreeView;
        private CancellationTokenSource? _sidebarTreeCts;
        private bool _suppressSidebarTreeSelection;
        private int _sidebarTreeScrollRequestVersion;
        private readonly Dictionary<string, string> _sidebarTreeSelectionMemory = new(StringComparer.OrdinalIgnoreCase);
        private bool _suppressSidebarNavSelection;
        private EntryViewModel? _pendingContextRenameEntry;
        private EntriesContextRequest? _entriesContextRequest;
        private EntryViewModel? _lastEntriesContextItem;
        private EntriesContextRequest? _pendingEntriesContextRequest;
        private PendingEntriesContextCommand? _pendingEntriesContextCommand;
        private readonly FavoritesController _favoritesController = new();
        private readonly DirectorySessionController _directorySessionController = new();
        private readonly FileOperationsController _fileOperationsController = new();
        private readonly SettingsController _settingsController = new();
        private readonly WatcherController _watcherController = new();
        private readonly FileCommandCatalog _fileCommandCatalog = new();
        private readonly InlineEditCoordinator _inlineEditCoordinator = new();
        private readonly DelegateCommand _entriesContextCommand;
        private InlineEditSession? _entriesRenameInlineSession;
        private InlineEditSession? _sidebarTreeRenameInlineSession;
        private InlineEditSession? _addressInlineSession;
        private SidebarTreeEntry? _pendingSidebarTreeContextEntry;
        private TreeViewNode? _activeSidebarTreeContextNode;
        private MenuFlyoutItem? _sidebarTreeExpandMenuItem;
        private MenuFlyoutItem? _sidebarTreeCollapseMenuItem;
        private MenuFlyoutSeparator? _sidebarTreeExpandCollapseSeparator;
        private Canvas? _sidebarTreeRenameOverlayCanvas;
        private Border? _sidebarTreeRenameOverlayBorder;
        private TextBox? _sidebarTreeRenameTextBox;
        private ControlTemplate? _renameOverlayTextBoxTemplate;
        private SidebarTreeEntry? _activeSidebarTreeRenameEntry;
        private bool _isCommittingSidebarTreeRename;
        private bool _isSidebarSelectionActive;
        private bool _isEntriesSelectionActive = true;
        private readonly SelectionSurfaceCoordinator _selectionSurfaceCoordinator =
            new(SelectionSurfaceId.Sidebar);

        private const double SidebarExpandedDefaultWidth = 220;
        private const double SidebarExpandedMinWidth = 32;
        private const double SidebarCompactWidth = 40;
        private const double SidebarCompactThreshold = SidebarCompactWidth;
        private const double SidebarCompactExitThreshold = SidebarCompactWidth + 24;
        private const double SidebarSplitterWidth = 0;
        private const double SidebarMinContentWidth = 520;
        private const int SidebarTreeMaxChildren = 5000;
        private const string ShellMyComputerPath = "shell:mycomputer";
        private const double SidebarTreeRenameOffsetX = -2;
        private const double SidebarTreeRenameOffsetY = 0;
        private const double SidebarTreeRenameTextMarginTopOffset = 1;
        private const double SidebarTreeRenameMinWidth = 140;
        private const double SidebarTreeRenameWidthPadding = 12;
        private const double SidebarTreeRenameRightMargin = 8;
        private const double GroupedListColumnSpacing = 12;
        private static readonly DataTemplate SidebarTreeItemTemplate = CreateSidebarTreeItemTemplate();

        public event PropertyChangedEventHandler? PropertyChanged;

        private const uint InitialPageSize = 96;
        private const uint MinPageSize = 64;
        private const uint MaxPageSize = 1000;
        private readonly BatchObservableCollection<EntryViewModel> _entries = new();
        private readonly ObservableCollection<GroupedEntryColumnViewModel> _groupedEntryColumns = new();
        private readonly List<EntryViewModel> _presentationSourceEntries = new();
        private bool _presentationSourceInitialized;
        private List<GroupedEntryColumnViewModel>? _groupedColumnsProjectionCache;
        private int _presentationSourceVersion;
        private int _groupedColumnsCacheSourceVersion = -1;
        private EntrySortField _groupedColumnsCacheSortField;
        private SortDirection _groupedColumnsCacheSortDirection;
        private EntryGroupField _groupedColumnsCacheGroupField;
        private readonly EntriesPresentationBuilder _entriesPresentationBuilder = new();
        private readonly EntriesRepeaterLayoutProfile _detailsRepeaterLayoutProfile;
        private readonly FixedExtentVirtualizingLayout _detailsVirtualizingLayout;
        private readonly GroupedListRepeaterLayoutProfile _groupedRepeaterLayoutProfile;
        private readonly GroupedListVirtualizingLayout _groupedVirtualizingLayout;
        private IEntriesViewHost? _detailsEntriesViewHost;
        private IEntriesViewHost? _groupedEntriesViewHost;
        private NavigationPerfSession? _activeNavigationPerfSession;
        public ObservableCollection<BreadcrumbItemViewModel> Breadcrumbs { get; } = new();
        public ObservableCollection<BreadcrumbItemViewModel> VisibleBreadcrumbs { get; } = new();
        private ulong _nextCursor;
        private bool _hasMore;
        private bool _isLoading;
        private bool _entriesFlyoutOpen;
        private CommandMenuFlyout? _activeEntriesContextFlyout;
        private string _currentPath = ShellMyComputerPath;
        private string? _selectedEntryPath;
        private string? _focusedEntryPath;
        private string? _pendingParentReturnAnchorPath;
        private string? _pendingHistoryStateRestorePath;
        private readonly Dictionary<string, DirectoryViewState> _directoryViewStates = new(StringComparer.OrdinalIgnoreCase);
        private uint _currentPageSize = InitialPageSize;
        private uint _lastFetchMs;
        private uint _totalEntries;
        private DirectorySortMode _currentSortMode = DirectorySortMode.FolderFirstNameAsc;
        private EntryViewMode _currentViewMode = EntryViewMode.Details;
        private EntrySortField _currentSortField = EntrySortField.Name;
        private SortDirection _currentSortDirection = SortDirection.Ascending;
        private EntryGroupField _currentGroupField = EntryGroupField.None;
        private ShellMode _shellMode = ShellMode.Explorer;
        private SettingsSection _currentSettingsSection = SettingsSection.General;
        private bool _suppressSettingsNavigationSelection;
        private readonly AppSettingsService _appSettingsService = new();
        private AppSettings _appSettings = new();
        private EntryViewDensityMode _currentEntryViewDensityMode = EntryViewDensityMode.Normal;
        private double _lastDetailsHorizontalOffset = double.NaN;
        private double _lastDetailsVerticalOffset = double.NaN;
        private double _lastGroupedHorizontalOffset = double.NaN;
        private double _lastGroupedVerticalOffset = double.NaN;
        private double _lastDetailsVerticalDelta;
        private int _lastDetailsViewportStartIndex = -1;
        private int _lastDetailsViewportIndexDelta;
        private double _estimatedItemHeight = 32.0;
        private int _groupedListRowsPerColumn = -1;
        private readonly Stack<string> _backStack = new();
        private readonly Stack<string> _forwardStack = new();
        private string _currentQuery = string.Empty;
        private readonly ExplorerService _explorerService = new();
        private readonly FileManagementCoordinator _fileManagementCoordinator;
        private IEntryResultSet? _activeEntryResultSet;
        private readonly HashSet<string> _suppressedWatcherRefreshPaths = new(StringComparer.OrdinalIgnoreCase);
        private readonly object _sparseViewportGate = new();
        private int? _pendingSparseViewportTargetIndex;
        private bool _pendingSparseViewportPreferMinimalPage;
        private bool _isSparseViewportLoadActive;
        private readonly string _engineVersion;
        private EntryViewModel? _activeRenameOverlayEntry;
        private EntryViewModel? _pendingCreatedEntrySelection;
        private bool _isCommittingRenameOverlay;
        private RustUsnCapability _usnCapability;
        private FileSystemWatcher? _dirWatcher;
        private CancellationTokenSource? _watcherDebounceCts;
        private readonly Dictionary<string, FileSystemWatcher> _favoriteWatchers = new(StringComparer.OrdinalIgnoreCase);
        private CancellationTokenSource? _navigationLoadCts;
        private CancellationTokenSource? _directoryLoadCts;
        private CancellationTokenSource? _metadataPrefetchCts;
        private bool _localizedUiRefreshScheduled;
        private bool _localizedUiRefreshPending;
        private int _localizedUiRefreshVersion;
        private int _localizedUiDeferredRefreshVersion;
        private int _metadataViewportRequestVersion;
        private long _directorySnapshotVersion;
        private long _lastDetailsScrollInteractionTick;
        private CommandDockSide _commandDockSide = CommandDockSide.Top;
        private bool _showCommandDock = false;
        private bool _sidebarInitialized;
        private long _lastWatcherRefreshTick;
        private bool _allowActualClose;
        private bool _isHiddenToTray;
        private bool _trayIconAdded;
        private int _lastRestoredWindowWidth;
        private int _lastRestoredWindowHeight;
        private bool _windowSizeRestorePending;
        private bool _hasSeenFirstActivation;
        private bool _groupedColumnsRefreshQueued;
        private CancellationTokenSource? _groupedColumnsResizeDebounceCts;
        private int _groupedColumnsRefreshVersion;
        private long _lastGroupedColumnsRefreshAppliedStamp;
        private double _lastWindowWidth = double.NaN;
        private double _lastWindowHeight = double.NaN;
        private double _lastGroupedViewportHeight = double.NaN;
        private long _lastGroupedColumnsLiveResizeRefreshTick;
        private readonly Dictionary<string, NavigationViewItem> _sidebarPathButtons = new(StringComparer.OrdinalIgnoreCase);
        private readonly HashSet<string> _sidebarQuickAccessPaths = new(StringComparer.OrdinalIgnoreCase);
        private readonly HashSet<string> _sidebarDrivePaths = new(StringComparer.OrdinalIgnoreCase);
        private readonly Dictionary<string, bool> _groupExpansionStates = new(StringComparer.Ordinal);
        private readonly WorkspaceShellState _workspaceShellState = new();
        private readonly WorkspaceLayoutHost _workspaceLayoutHost;
        private DataTransferManager? _shareDataTransferManager;
        private FileCommandTarget? _pendingShareTarget;
        private IntPtr _windowHandle;
        private IntPtr _originalWndProc;
        private WndProcDelegate? _wndProcDelegate;
        private MenuFlyout? _activeBreadcrumbFlyout;
        private readonly List<BreadcrumbItemViewModel> _hiddenBreadcrumbItems = new();
        private bool _breadcrumbWidthsReady;
        private int _breadcrumbVisibleStartIndex = -1;
        private bool _lastTitleWasReadFailed;
        private readonly SemaphoreSlim _statusDialogSemaphore = new(1, 1);
        private DispatcherTimer? _renameInputTeachingTipTimer;
        private DispatcherTimer? _addressInputTeachingTipTimer;
        private bool _suppressRenameTextFiltering;
        private Controls.ModalActionDialog? _pasteConflictDialog;
    }
}
